### ISSUE TITLE
VRAM buildup after generating.

### ISSUE THREAD

**Issue by ShimamuX** [diodiogod/TTS-Audio-Suite#158]
> It's there—the VRAM buildup every time after generating.
> 
> **1st run** after unload model and & Free Model and cache :
> <img width="819" height="200" alt="Image" src="https://github.com/user-attachments/assets/f2b731ef-8cb6-4fe6-9964-3cae11312d96" />
> 
> **2nd run** after unload and clear :
> <img width="991" height="178" alt="Image" src="https://github.com/user-attachments/assets/26dba3a5-2113-4c63-a42c-ce8f094d51d5" />
> 
> **3rd run** :
> <img width="568" height="169" alt="Image" src="https://github.com/user-attachments/assets/3ec42f3a-fd89-48ec-9660-ec29baa6633a" />
> 
> and so on, till torch.OutOfMemoryError: Allocation on device
> 
> 
>  

 _Originally posted by @ShimamuX in [#98](https://github.com/diodiogod/TTS-Audio-Suite/issues/98#issuecomment-3485473119)_

**Comment by ShimamuX** [comment]
and cause : 
♻️ Using cached Hubert model
🔄 Reloading cached Hubert model from cpu to cuda
✅ Re-registered Hubert model with ComfyUI model management
🔧 RVC: rmvpe method requires RMVPE model, checking availability...
✅ RMVPE model already exists: E:\Ai\ComfyUI\ComfyUI\models\TTS\RVC\rmvpe.pt
✅ RMVPE model ready at: E:\Ai\ComfyUI\ComfyUI\models\TTS\RVC\rmvpe.pt
vc_single unused args: {}
🔧 vc_single: Starting conversion - version: v2, f0_method: rmvpe
🔧 RVC Audio: Resampled 44100Hz -> 16000Hz using torchaudio
🔧 vc_single: About to call vc.pipeline - if_f0: 1
Using preloaded file index.
get_f0 rmvpe unused params: {}
vc torch.Size([1, 6720, 768]) torch.Size([1, 6720]) torch.Size([1, 6720])
❌ vc_single: Pipeline error: Allocation on device
🔧 Pipeline error type: OutOfMemoryError
Traceback (most recent call last):
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\vc_infer_pipeline.py", line 333, in vc_single
        audio_opt = vc.pipeline(
                    ~~~~~~~~~~~^
        hubert_model,
        ^^^^^^^^^^^^^
    ...<17 lines>...
        f0_file=f0_file,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\vc_infer_pipeline.py", line 179, in pipeline
    audio_opt.append(self.vc(model, net_g, sid, audio_slice, pitch_slice, pitchf_slice, times, index, big_npy, index_rate, version, protect)[self.t_pad_tgt : -self.t_pad_tgt])
                     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\vc_infer_pipeline.py", line 106, in vc
    (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\lib\infer_pack\models.py", line 800, in infer
    m_p, logs_p, x_mask = self.enc_p(phone, pitch, phone_lengths)
                          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\lib\infer_pack\models.py", line 101, in forward
    x = self.encoder(x * x_mask, x_mask)
  File "E:\Ai\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\lib\infer_pack\attentions.py", line 61, in forward
    y = self.attn_layers[i](x, x, attn_mask)
  File "E:\Ai\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\lib\infer_pack\attentions.py", line 217, in forward
    x, self.attn = self.attention(q, k, v, mask=attn_mask)
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\lib\infer_pack\attentions.py", line 261, in attention
    relative_weights = self._absolute_position_to_relative_position(p_attn)
  File "E:\Ai\ComfyUI\ComfyUI\custom_nodes\tts_audio_suite\engines\rvc\impl\lib\infer_pack\attentions.py", line 342, in _absolute_position_to_relative_position
    x_flat = F.pad(x_flat, convert_pad_shape([[0, 0], [0, 0], [length, 0]]))
  File "E:\Ai\ComfyUI\python_embeded\Lib\site-packages\torch\nn\functional.py", line 5290, in pad
    return torch._C._nn.pad(input, pad, mode, value)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device
❌ RVC conversion returned None
❌ RVC conversion failed: RVC conversion failed - no output from minimal wrapper

**Comment by diodiogod** [comment]
## Issue Resolved ✅

**Version 4.14.12** - VRAM buildup fix deployed

### Root Cause
Pitch extraction models (RMVPE, FCPE) were cached as instance variables in the `VC/FeatureExtractor` class and never explicitly freed between conversions. Each conversion would accumulate intermediate tensors in VRAM, causing progressive memory buildup.

### Solution Implemented
Modified `engines/rvc/minimal_reference_wrapper.py` to explicitly clear pitch extraction model cache after each conversion completes:
- Delete cached RMVPE and FCPE models from the VC instance
- Force garbage collection
- Clear CUDA cache

This preserves the performance benefit of caching RVC and Hubert models while preventing pitch extraction models from accumulating in VRAM.

### Testing
- Tested with multiple consecutive RVC conversions using different pitch extraction methods (RMVPE, FCPE, Crepe, PM)
- No VRAM accumulation observed after many generations
- Pitch models (RMVPE, FCPE) are now being cleared after each conversion
- Model caching performance maintained

Note: The system tested has abundant VRAM (24GB), so visible accumulation is harder to detect, but the fix ensures pitch models are properly freed after each conversion.

The fix is now available in v4.14.12.

**Comment by diodiogod** [comment]
Please test and report back!

**Comment by diodiogod** [comment]
Great work debugging this VRAM accumulation issue! Your approach was solid in identifying that pitch extraction models were the main culprit and needed cleanup.

## Solution Approach

For the final implementation, we followed **ComfyUI's architecture philosophy** rather than aggressive unloading:

**What we do:**
- ✅ Register RVC and Hubert models with ComfyUI's model management system
- ✅ Clear pitch extraction models after each conversion (RMVPE, FCPE, Crepe) - these are the main accumulators
- ✅ Keep RVC/Hubert models cached for performance (same model reuses avoid reload overhead)
- ✅ Let ComfyUI's `free_memory()` intelligently unload models when VRAM is actually needed

**What we don't do:**
- ❌ Unload models on every conversion (defeats caching benefit)
- ❌ Force reload when the same model is used again

## How Unloading Works

When ComfyUI detects VRAM pressure, it automatically calls `free_memory()` which:
1. Unloads models registered in ComfyUI's `current_loaded_models` list
2. Respects model priority and usage patterns
3. Only unloads when necessary (smart, not aggressive)

## Manual Cleanup

The **"Clear VRAM"** button in ComfyUI Manager will also:
- Unload all RVC voice conversion models
- Unload Hubert feature extraction models  
- Clear pitch extractors (RMVPE, FCPE, Crepe)

## Testing

If you still experience VRAM accumulation after this release:
1. Let us know the VRAM usage pattern you're seeing
2. We can enable additional monitoring if needed
3. The approach should match other TTS engines (ChatterBox, F5-TTS, VibeVoice) which use the same pattern

Fixed in v4.14.16

**Comment by diodiogod** [comment]
Just to explain this a little more, you should see VRAM accumulation, it should be normal. But it SHOULD unload when needed. That is the correct behavior. Please test and report back! and thanks again for the dedication in trying to fix it yourself!

**Comment by diodiogod** [comment]
@ShimamuX can you please test again in your system and check if the current implementation fit your needs? Thanks
